// mapping response code
const rcSuccess        = '0';
const rcError          = '99';
const rcUnauthorized   = '01';
const rcForbidden      = '02';
const rcNotFound       = '03';
const rcTimeout        = '04';
const rcNetworkError   = '05';
const rcServerError    = '06';
const rcEmptyData      = '07';
